DEBUG

diff --git a/.github/workflows/run-integration-tests.yml b/.github/workflows/run-integration-tests.yml
--- a/.github/workflows/run-integration-tests.yml
+++ b/.github/workflows/run-integration-tests.yml
@@ -24,89 +24,89 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  persistence:
-    strategy:
-      fail-fast: false
-      matrix:
-        project: [persistence-it-hibernate]
-        parallel: [0, 2]
-        pre-start: [false, true]
-        java: [21]
-        include:
-          - project: persistence-it-eclipselink
-            parallel: 2
-            pre-start: true
-            java: 21
-    name: "persistence (${{matrix.project}}, ${{matrix.parallel}}, ${{matrix.pre-start}}, ${{matrix.java}})"
-    runs-on: ubuntu-latest
-    if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')) }}
-    timeout-minutes: 10
-    permissions:
-      contents: read
-    steps:
-    - uses: actions/checkout@v7
+  # persistence:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       project: [persistence-it-hibernate]
+  #       parallel: [0, 2]
+  #       pre-start: [false, true]
+  #       java: [21]
+  #       include:
+  #         - project: persistence-it-eclipselink
+  #           parallel: 2
+  #           pre-start: true
+  #           java: 21
+  #   name: "persistence (${{matrix.project}}, ${{matrix.parallel}}, ${{matrix.pre-start}}, ${{matrix.java}})"
+  #   runs-on: ubuntu-latest
+  #   if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')) }}
+  #   timeout-minutes: 10
+  #   permissions:
+  #     contents: read
+  #   steps:
+  #   - uses: actions/checkout@v7
 
-    - name: Set up JDK
-      uses: actions/setup-java@v5
-      with:
-        distribution: temurin
-        java-version: ${{ matrix.java }}
+  #   - name: Set up JDK
+  #     uses: actions/setup-java@v5
+  #     with:
+  #       distribution: temurin
+  #       java-version: ${{ matrix.java }}
 
-    - name: Cache Maven
-      uses: actions/cache@v6
-      with:
-        path: ~/.m2/repository
-        key: ${{ runner.os }}-mvn-it-build-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
+  #   - name: Cache Maven
+  #     uses: actions/cache@v6
+  #     with:
+  #       path: ~/.m2/repository
+  #       key: ${{ runner.os }}-mvn-it-build-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
 
-    - name: Restore docker image cache
-      uses: actions/cache/restore@v6
-      id: restore-docker-image-cache
-      with:
-        path: ~/.cache/docker/
-        key: ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
-          ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-
+  #   - name: Restore docker image cache
+  #     uses: actions/cache/restore@v6
+  #     id: restore-docker-image-cache
+  #     with:
+  #       path: ~/.cache/docker/
+  #       key: ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
+  #       restore-keys: |
+  #         ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
+  #         ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-
 
-    - name: Load docker image cache
-      run: |
-        echo "Deleting preinstalled images" && docker image ls
-        docker image prune -af
+  #   - name: Load docker image cache
+  #     run: |
+  #       echo "Deleting preinstalled images" && docker image ls
+  #       docker image prune -af
 
-        cat ~/.cache/docker/images.tar | docker load && echo "Restored docker image cache" && docker image ls || true
+  #       cat ~/.cache/docker/images.tar | docker load && echo "Restored docker image cache" && docker image ls || true
 
-    - name: Test
-      run: |
-        ./mvnw -B test \
-        -pl "advanced-demo/integration-tests/${{ matrix.project }}" -am \
-        -P run-it \
-        ${{ matrix.pre-start && '-Dinfra-pre-start.enabled=1 ' || '' }} \
-        ${{ matrix.parallel > 0 && format('-Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.parallel.mode.default=concurrent -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -Djunit.jupiter.execution.parallel.config.strategy=fixed -Djunit.jupiter.execution.parallel.config.fixed.parallelism=2 -Djunit.jupiter.execution.parallel.config.fixed.max-pool-size={0} ', matrix.parallel) || '' }}
+  #   - name: Test
+  #     run: |
+  #       ./mvnw -B test \
+  #       -pl "advanced-demo/integration-tests/${{ matrix.project }}" -am \
+  #       -P run-it \
+  #       ${{ matrix.pre-start && '-Dinfra-pre-start.enabled=1 ' || '' }} \
+  #       ${{ matrix.parallel > 0 && format('-Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.parallel.mode.default=concurrent -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -Djunit.jupiter.execution.parallel.config.strategy=fixed -Djunit.jupiter.execution.parallel.config.fixed.parallelism=2 -Djunit.jupiter.execution.parallel.config.fixed.max-pool-size={0} ', matrix.parallel) || '' }}
 
-    - name: Create docker image cache
-      # Cache can't be saved when it's already present
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: |
-        echo "Images before pruning" && docker image ls
-        docker image prune -af --filter "until=2160h"
-        docker image prune -f
-        echo "Currently available images" && docker image ls
+  #   - name: Create docker image cache
+  #     # Cache can't be saved when it's already present
+  #     if: steps.cache.outputs.cache-hit != 'true'
+  #     run: |
+  #       echo "Images before pruning" && docker image ls
+  #       docker image prune -af --filter "until=2160h"
+  #       docker image prune -f
+  #       echo "Currently available images" && docker image ls
 
-        echo "Will NOT cache images" && docker image ls -f="label=org.testcontainers.sessionId"
+  #       echo "Will NOT cache images" && docker image ls -f="label=org.testcontainers.sessionId"
 
-        mkdir -p ~/.cache/docker
-        image_ids_to_save=$(comm -23 <(docker images -q | sort) <(docker image ls -q -f="label=org.testcontainers.sessionId" | sort))
-        echo "Saving image ids" && echo $image_ids_to_save
-        docker save $image_ids_to_save -o ~/.cache/docker/images.tar
+  #       mkdir -p ~/.cache/docker
+  #       image_ids_to_save=$(comm -23 <(docker images -q | sort) <(docker image ls -q -f="label=org.testcontainers.sessionId" | sort))
+  #       echo "Saving image ids" && echo $image_ids_to_save
+  #       docker save $image_ids_to_save -o ~/.cache/docker/images.tar
 
-        ls -lha ~/.cache/docker
+  #       ls -lha ~/.cache/docker
 
-    - name: Save docker image cache
-      if: steps.cache.outputs.cache-hit != 'true'
-      uses: actions/cache/save@v6
-      with:
-        path: ~/.cache/docker/
-        key: ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
+  #   - name: Save docker image cache
+  #     if: steps.cache.outputs.cache-hit != 'true'
+  #     uses: actions/cache/save@v6
+  #     with:
+  #       path: ~/.cache/docker/
+  #       key: ${{ runner.os }}-it-docker-images-persistence-${{ matrix.project }}-${{ hashFiles('**/pom.xml') }}
 
   selenium:
     strategy:
@@ -169,7 +169,6 @@ jobs:
       run: |
         echo "Images before pruning" && docker image ls
         docker image prune -af --filter "until=2160h"
-        docker image prune -f
         echo "Currently available images" && docker image ls
 
         echo "Will NOT cache images" && docker image ls -f="label=org.testcontainers.sessionId"
